### ISSUE TITLE
Weight Axis variable font

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/josefinslab#1]
@sannorozco,

Hi Santiago,

As you know the Google fonts team have commissioned Type Network to make a weight axis variable font of ‘JosefinSlab'. 

In order to achieve the highest quality and most efficient long term results we will be converting the original source data over to UFO. The new source data will be generated in the RoboFont environment using fontmake and ttfautohint. There has been progress on tools to make an easy path to move between the Glyphs and Robofont environment.

During the process we will be looking to improve any errors while preserving how the font appears and renders on different platforms.

We were not able to find an independent git repository for this family. We have started by creating a new git repository which will later transfer ownership over to Google. When the proposed final font is approved by Google will you accept a pull request?

We hope this answers some of your questions about the process. Please let us know if you have any additional comments.

Best Regards,

Jill Pichotta
Type Network, VP
pichotta@typenetwork.com

**Comment by sannorozco** [comment]
Hi Jill!
Yes, all this sounds good! 🙂
