### ISSUE TITLE
Original Sources and Interpolation

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/josefinslab#2]
Hi Santiago,

As mentioned, we are not able to locate a git repository with sources for **Josefin Slab**.

We have started by converting the VFBs from a old-goggle font directory on bitbucket over to UFOs.

Unfortunately, this bitbucket location is missing a VFB for the Regular and Bold Italic.

1)  Do you know of any more recent VFB sources for all styles?

2) Do you recall if there is an intermediate master in this family such as the Regular?
or, are there four original extreme poles?  
Thin
Thin Italic
Bold
BoldItalic

3) Were there any manual manipulations between the Thin and Bold weight?

4) Lastly, if the intermediates were interpolated do you have record of the interpolation values?

Thank you,

Jill

<img width="769" alt="Josefin Slab 2019-10-15 at 11 59 24 AM" src="https://user-images.githubusercontent.com/6576107/66848948-ff80f700-ef43-11e9-9433-895f2a82c99f.png">

**Comment by sannorozco** [comment]
I Jill, I found the sources I sent to google, these were sent fo me after iKern.

1. here are the sources [JosefinSlab-iKern.zip](https://github.com/TypeNetwork/josefinslab/files/3730720/JosefinSlab-iKern.zip)

2. There’s no intermediates, just the extremes you mention

3. no manual editing

4. form those 4 poles, I don’t remember the interpolation values, they should be defined in the MM settings on those poles.
