### ISSUE TITLE
VFB Conversion < SO

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/josefinslab#3]
Hi @cjdunn,

The previous conversion of VFBs from bitbucket/old-googlefontdirectory to UFOs was missing sources for the Regular and Bold Italic.

Could you please convert these VFBs supplied by Typemade to UFOs?  
In the foldre on this repo: 'sources ufo conv < SO VFBs'

There are some duplicate sources which will need to be verified after conversion.

**Comment by cjdunn** [comment]
OK, will do

**Comment by pichotta** [comment]
The original ikern versions had a folder with the notation of 'Fix'.  These three sources did have a fix to the outline of the /w and the lc caron accented char fitting. The fix styles have been integrated and have replaced the previous versions.

![Slab :w fix](https://user-images.githubusercontent.com/6576107/66939392-fdd13500-f010-11e9-9180-ba72dc0790d8.png)

JosefinSlabFix-ThinItalic_ik.ufo
JosefinSlabFix-Italic_ik.ufo
JosefinSlabFix-LightItalic_fik.ufo
