### ISSUE TITLE
Thin difference

### ISSUE THREAD

**Issue by djrrb** [TypeNetwork/josefinslab#7]
Diffenator shows a difference for the Thin:

![glyphs_modified](https://user-images.githubusercontent.com/6578861/91321584-c7198e80-e78c-11ea-8ada-c84d36ca1279.gif)

I remember this happened in Josefin Sans too, something about the lightest instance not being the same as the lightest source, or something about autohinting, or something.

**Comment by pichotta** [comment]
@moyogo
Do you have insight into why the diff report shows a weight difference in the Thin?

**Comment by moyogo** [comment]
font-diffenator uses the OS/2 weightClass values to match styles. Since the Josefin Slab Thin on Google Fonts currently has a weightclass = 250, diffenator compares it with the new fonts that has weightClass = 300 because of rounding.

**Comment by moyogo** [comment]
For future record, Marc said to upgrade diffenator as this has been fixed in a newer version.
