### ISSUE TITLE
Update vertical metrics

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/josefinslab#9]
Please enable fsSelection bit 7 and update the vertical metrics. The metrics currently don't have the same visual appearance as the fonts hosted Google Fonts.

![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/7525512/92099663-b1324c00-edd2-11ea-9838-19b2d3c3bd2d.gif)

Everything else looks good.

**Comment by m4rc1e** [comment]
I'm still getting the same issue

![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/7525512/94801641-3c0c6380-03de-11eb-8b9a-93dadba2833d.gif)

Do the old static fonts have different metrics for the Italics?

**Comment by m4rc1e** [comment]
ping @pichotta issue is still present. I'm wondering if the current static fonts have consistent vertical metrics?

**Comment by moyogo** [comment]
The current GF have different vertical metrics across weights:

weights | metrics | value
-- | -- | -- 
Regular, Bold | OS2.sTypoAscender, hhea.ascent | 750
Thin, Light | OS2.sTypoAscender, hhea.ascent | 931
SemiBold | OS2.sTypoAscender, hhea.ascent | 932
Thin, Light, Regular, SemiBold, Bold | OS2.sTypoDescender, hhea.descent | -250

The new version has the ascender values at 932 and the descender values at -250.

**Comment by m4rc1e** [comment]
Ok cool. Thanks!

**Comment by pichotta** [comment]
@marc1e  Since the originals have inconsistent metrics. Considering if we should make them consistent both within the family and also match the Sans.  The choice is 750 or 932 for the Ascender values.  Sans is at 750.

**Comment by m4rc1e** [comment]
@pichotta this sounds like a good idea to me. Josefin Sans VF has the following vert metrics with fsSelection bit 7 enabled:

```
    OS/2
    <sTypoAscender value="750"/>
    <sTypoDescender value="-250"/>
    <sTypoLineGap value="0"/>
    <usWinAscent value="1242"/> Please set to yMax
    <usWinDescent value="324"/> Please set to abs yMin

    hhea
    <ascent value="750"/>
    <descent value="-250"/>
    <lineGap value="0"/>
```

If we can copy this for the Slab, it would be most excellent.

**Comment by pichotta** [comment]
Great!  @moyogo   Can you make this adjustment in the 'vertmetrics' branch and build and then I will accept the PR?

**Comment by m4rc1e** [comment]
Ahh but Denis does raise a good point. The vertical metrics for Josefin Sans are very tight so I do wonder if this is a good idea.

**Comment by m4rc1e** [comment]
I don't want us to change the vertical metrics of Josefin sans tbh. People will complain.

**Comment by moyogo** [comment]
I regenerated the fonts with hhea and typo ascenders at 750. Here the gif from diffbrowser:
![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/1923747/96276364-cc47cc80-0fca-11eb-952c-e1e56e2d51d9.gif)

**Comment by pichotta** [comment]
@davelab6

Would you like to create an updated family named Josefin Slab **Neue**?

The current Josefin Slab that is being served has different vertical metrics within the family. See above. 
The Regular is at 750. 
The majority of styles are 932.
The default in the family is 100 Thin.
This family also does not have kerning.


The options being considered are:

• make all the Ascender vert metrics values equal 750. It is tight but would be the same as Josefin _Sans_ 

• make all the Ascender values 932


cc:
@moyogo 
@m4rc1e 
@djrrb

**Comment by pichotta** [comment]
Current build on Oct 28 uses vertical ascender value of 932.
